// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: proto/raftkv/raftkv.proto

package raftkv

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LogEntryData_Operation int32

const (
	LogEntryData_UNKOWN LogEntryData_Operation = 0
	LogEntryData_GET    LogEntryData_Operation = 1
	LogEntryData_SET    LogEntryData_Operation = 2
	LogEntryData_DELETE LogEntryData_Operation = 3
)

// Enum value maps for LogEntryData_Operation.
var (
	LogEntryData_Operation_name = map[int32]string{
		0: "UNKOWN",
		1: "GET",
		2: "SET",
		3: "DELETE",
	}
	LogEntryData_Operation_value = map[string]int32{
		"UNKOWN": 0,
		"GET":    1,
		"SET":    2,
		"DELETE": 3,
	}
)

func (x LogEntryData_Operation) Enum() *LogEntryData_Operation {
	p := new(LogEntryData_Operation)
	*p = x
	return p
}

func (x LogEntryData_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntryData_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_raftkv_raftkv_proto_enumTypes[0].Descriptor()
}

func (LogEntryData_Operation) Type() protoreflect.EnumType {
	return &file_proto_raftkv_raftkv_proto_enumTypes[0]
}

func (x LogEntryData_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntryData_Operation.Descriptor instead.
func (LogEntryData_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_raftkv_raftkv_proto_rawDescGZIP(), []int{0, 0}
}

type LogEntryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    LogEntryData_Operation `protobuf:"varint,1,opt,name=op,proto3,enum=api.proto.kv.LogEntryData_Operation" json:"op,omitempty"`
	Key   []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LogEntryData) Reset() {
	*x = LogEntryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_raftkv_raftkv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryData) ProtoMessage() {}

func (x *LogEntryData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raftkv_raftkv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryData.ProtoReflect.Descriptor instead.
func (*LogEntryData) Descriptor() ([]byte, []int) {
	return file_proto_raftkv_raftkv_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntryData) GetOp() LogEntryData_Operation {
	if x != nil {
		return x.Op
	}
	return LogEntryData_UNKOWN
}

func (x *LogEntryData) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LogEntryData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SnapshotItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SnapshotItem) Reset() {
	*x = SnapshotItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_raftkv_raftkv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotItem) ProtoMessage() {}

func (x *SnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raftkv_raftkv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotItem.ProtoReflect.Descriptor instead.
func (*SnapshotItem) Descriptor() ([]byte, []int) {
	return file_proto_raftkv_raftkv_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotItem) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SnapshotItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_raftkv_raftkv_proto protoreflect.FileDescriptor

var file_proto_raftkv_raftkv_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x6b, 0x76, 0x2f, 0x72,
	0x61, 0x66, 0x74, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x4c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45,
	0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x22,
	0x36, 0x0a, 0x0c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x6b, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_raftkv_raftkv_proto_rawDescOnce sync.Once
	file_proto_raftkv_raftkv_proto_rawDescData = file_proto_raftkv_raftkv_proto_rawDesc
)

func file_proto_raftkv_raftkv_proto_rawDescGZIP() []byte {
	file_proto_raftkv_raftkv_proto_rawDescOnce.Do(func() {
		file_proto_raftkv_raftkv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_raftkv_raftkv_proto_rawDescData)
	})
	return file_proto_raftkv_raftkv_proto_rawDescData
}

var file_proto_raftkv_raftkv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_raftkv_raftkv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_raftkv_raftkv_proto_goTypes = []interface{}{
	(LogEntryData_Operation)(0), // 0: api.proto.kv.LogEntryData.Operation
	(*LogEntryData)(nil),        // 1: api.proto.kv.LogEntryData
	(*SnapshotItem)(nil),        // 2: api.proto.kv.SnapshotItem
}
var file_proto_raftkv_raftkv_proto_depIdxs = []int32{
	0, // 0: api.proto.kv.LogEntryData.op:type_name -> api.proto.kv.LogEntryData.Operation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_raftkv_raftkv_proto_init() }
func file_proto_raftkv_raftkv_proto_init() {
	if File_proto_raftkv_raftkv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_raftkv_raftkv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_raftkv_raftkv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_raftkv_raftkv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_raftkv_raftkv_proto_goTypes,
		DependencyIndexes: file_proto_raftkv_raftkv_proto_depIdxs,
		EnumInfos:         file_proto_raftkv_raftkv_proto_enumTypes,
		MessageInfos:      file_proto_raftkv_raftkv_proto_msgTypes,
	}.Build()
	File_proto_raftkv_raftkv_proto = out.File
	file_proto_raftkv_raftkv_proto_rawDesc = nil
	file_proto_raftkv_raftkv_proto_goTypes = nil
	file_proto_raftkv_raftkv_proto_depIdxs = nil
}
